# Generated by Django 4.2.7 on 2023-12-08 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0006_alter_todo_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='no',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
    ]
